name: Build Flutter APK & AAB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: flutter build apk --split-per-abi --release

      - run: flutter build appbundle --release

      - uses: actions/upload-artifact@v4
        with:
          name: RandomFlutter-APKs
          path: build/app/outputs/flutter-apk/*.apk

      - uses: actions/upload-artifact@v4
        with:
          name: RandomFlutter-AAB
          path: build/app/outputs/bundle/release/*.aab
